#!/usr/bin/env bash

######################################################
#---------------------Auto start---------------------#
######################################################

sxhkd &
picom &
feh --bg-scale ~/Pictures/Wallpapers/LEP.png &
eww -c ~/.config/eww/bar open bar
xsetroot -cursor_name left_ptr &
/usr/bin/lxpolkit &
flameshot &

######################################################
#----------------------Workspace---------------------#
######################################################

bspc monitor HDMI-0 -d			1 2
bspc monitor DP-4 -d			3 4 5 6

######################################################
#-----------------------Config-----------------------#
######################################################

bspc config border_width            3
bspc config window_gap              6

bspc config focus_follows_pointer   true
bspc config pointer_modifier	    super

bspc config split_ratio             0.50

bspc config single_monocle          true
bspc config gapless_monocle         false
bspc config paddingless_monocle     true

bspc config presel_feedback_color   "#fd2e59"

bspc config normal_border_color     "#5e5f75"
bspc config active_border_color     "#9ba0cf"
bspc config focused_border_color    "#4f87c2"
