#!/usr/bin/env bash

######################################################
#---------------------Auto start---------------------#
######################################################

sxhkd &
picom &
feh --bg-scale ~/Pictures/Wallpapers/background.jpg &
~/.config/polybar/launch.sh &
xsetroot -cursor_name left_ptr &
/usr/bin/lxpolkit &
flameshot &
gwe --hide-window &

######################################################
#----------------------Workspace---------------------#
######################################################

bspc monitor HDMI-0 -d		    1 2
bspc monitor DP-0   -d		    3 4 5 6
#bspc monitor -d			1 2 3 4 5 6

######################################################
#----------------------Monitors----------------------#
######################################################

xrandr --output DP-0 --mode 1920x1080 --rate 143.61 --primary --pos 1920x0
xrandr --output HDMI-0 --mode 1920x1080 --rate 75.00 --pos 0x235

######################################################
#-----------------------Config-----------------------#
######################################################

bspc config border_width            3
bspc config window_gap              6

bspc config focus_follows_pointer   true
bspc config pointer_modifier	    super

bspc config split_ratio             0.50

bspc config single_monocle          true
bspc config gapless_monocle         false
bspc config paddingless_monocle     true

bspc config presel_feedback_color   "#fd2e59"

bspc config normal_border_color     "#5e5f75"
bspc config active_border_color     "#9ba0cf"
bspc config focused_border_color    "#4f87c2"
